// #[fail_quietly]
try {
    risky_operation()
} catch e {
    "error occurred"
}